### PR TITLE
fix: copy python folder over as well

### PR DESCRIPTION
**Pull request by tuananh**
native module (node-gyp) requires python

```
COPY --from=development /opt/bitnami/python /opt/bitnami/python
```

### CODE REVIEW

**Comment by prydonius** [comment]
cc @sameersbn

**Comment by prydonius** [comment]
see also discussion in #109

**Comment by sameersbn** [comment]
@tuananh With the `prod` images we intend to provide a minimal node distribution for production use. I acknowledge that you need to have python installed for your particular use-case and probably you also need other build tools (gcc, make, etc.). Please consider installing python (and other packages) from apt sources. The following should work.

```
FROM bitnami/node:8-prod
RUN install_packages python
``

Do you think this is a solution that you can adopt?

**Comment by tuananh** [comment]
@sameersbn i think that would quite defeat the purpose of having `prod` image. so i do as @prydonius suggest and use multi stage docker build with development image as builder and copy over to `prod` image.

**Comment by sameersbn** [comment]
@tuananh Yes. That's right. You have picked the most ideal solution.
I think we should close this pr don't you think?

**Pull request closed without merging**
